/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OmaAmbulanceCertsApp {
        "apiBase": string;
        "basePath": string;
    }
    interface OmaAmbulanceCertsList {
        "apiBase": string;
        "certificationId": string;
    }
    interface OmaAmbulanceCertsUserList {
        "apiBase": string;
        "userId": string;
    }
}
export interface OmaAmbulanceCertsListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOmaAmbulanceCertsListElement;
}
declare global {
    interface HTMLOmaAmbulanceCertsAppElement extends Components.OmaAmbulanceCertsApp, HTMLStencilElement {
    }
    var HTMLOmaAmbulanceCertsAppElement: {
        prototype: HTMLOmaAmbulanceCertsAppElement;
        new (): HTMLOmaAmbulanceCertsAppElement;
    };
    interface HTMLOmaAmbulanceCertsListElementEventMap {
        "error-event": string;
    }
    interface HTMLOmaAmbulanceCertsListElement extends Components.OmaAmbulanceCertsList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOmaAmbulanceCertsListElementEventMap>(type: K, listener: (this: HTMLOmaAmbulanceCertsListElement, ev: OmaAmbulanceCertsListCustomEvent<HTMLOmaAmbulanceCertsListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOmaAmbulanceCertsListElementEventMap>(type: K, listener: (this: HTMLOmaAmbulanceCertsListElement, ev: OmaAmbulanceCertsListCustomEvent<HTMLOmaAmbulanceCertsListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOmaAmbulanceCertsListElement: {
        prototype: HTMLOmaAmbulanceCertsListElement;
        new (): HTMLOmaAmbulanceCertsListElement;
    };
    interface HTMLOmaAmbulanceCertsUserListElement extends Components.OmaAmbulanceCertsUserList, HTMLStencilElement {
    }
    var HTMLOmaAmbulanceCertsUserListElement: {
        prototype: HTMLOmaAmbulanceCertsUserListElement;
        new (): HTMLOmaAmbulanceCertsUserListElement;
    };
    interface HTMLElementTagNameMap {
        "oma-ambulance-certs-app": HTMLOmaAmbulanceCertsAppElement;
        "oma-ambulance-certs-list": HTMLOmaAmbulanceCertsListElement;
        "oma-ambulance-certs-user-list": HTMLOmaAmbulanceCertsUserListElement;
    }
}
declare namespace LocalJSX {
    interface OmaAmbulanceCertsApp {
        "apiBase"?: string;
        "basePath"?: string;
    }
    interface OmaAmbulanceCertsList {
        "apiBase"?: string;
        "certificationId"?: string;
        "onError-event"?: (event: OmaAmbulanceCertsListCustomEvent<string>) => void;
    }
    interface OmaAmbulanceCertsUserList {
        "apiBase"?: string;
        "userId"?: string;
    }
    interface IntrinsicElements {
        "oma-ambulance-certs-app": OmaAmbulanceCertsApp;
        "oma-ambulance-certs-list": OmaAmbulanceCertsList;
        "oma-ambulance-certs-user-list": OmaAmbulanceCertsUserList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "oma-ambulance-certs-app": LocalJSX.OmaAmbulanceCertsApp & JSXBase.HTMLAttributes<HTMLOmaAmbulanceCertsAppElement>;
            "oma-ambulance-certs-list": LocalJSX.OmaAmbulanceCertsList & JSXBase.HTMLAttributes<HTMLOmaAmbulanceCertsListElement>;
            "oma-ambulance-certs-user-list": LocalJSX.OmaAmbulanceCertsUserList & JSXBase.HTMLAttributes<HTMLOmaAmbulanceCertsUserListElement>;
        }
    }
}
